
export const Libros = [
                {id: "1", nombre: "El niño", autor: "Fernando Aramburu", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/00b3ff1b-a928-4ff1-8296-df12eae6aac1/d_360_620/portada_el-nino_fernando-aramburu_202402281541.webp", sinopsis: "Un accidente real en el País Vasco de los años ochenta, la vida devastada de una familia. Una historia emocionante, adictiva y conmovedora, como solo Aramburu sabe contar.", valor: 35.23},
                {id: "2", nombre: "Lo que pasó", autor: "Javier Ruescas", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/9f32dd64-b4cb-4fd6-93a2-cb6f856626ad/d_360_620/portada_lo-que-paso_javier-ruescas_202403251029.webp", sinopsis: "La novela más personal de Javier Ruescas está inspirada en un suceso real que vivió junto a su pareja, ni más ni menos que una agresión motivada por la identidad de género. De ello nos habla en este libro que toca el tema de la homofobia y la injusticia sistémica. Desde el inicio, el libro atrapa al lector por como muestra las repercusiones del incidente en la vida de los personajes involucrados.", valor: 22.13},
                {id: "3", nombre: "Esto no está pasando", autor: "Carmen Romero", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/aaa8e031-9eb7-4513-9c93-47f9c8489fad/d_295_510/portada_esto-no-esta-pasando_carmen-romero_202404040742.webp", sinopsis: "Es junio de 2016, y el mundo de Carmen Romero se desmorona. Miguel ―su hermano, de solo veintiséis años, militar de profesión― se quita la vida al saltar por la ventana de la casa familiar mientras ven juntos El Padrino. Todo ocurre muy rápido; tanto que las cosas que hasta entonces tenían sentido dejan de tenerlo. Carmen cree vivir en una ficción: policía, vecinos, médicos, ambulancias y hasta su madre y su hermana participan del rodaje de una película en la que nadie dice: «¡Corten!».", valor: 22.23},
                {id: "4", nombre: "Prohibida en Normandía", autor: "Rosario Raro", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/6d9d376e-a8dc-4cf0-99b8-b7c7f065327c/d_295_510/portada_prohibida-en-normandia_rosario-raro_202403121801.webp", sinopsis: "Una novela basada en hechos reales que conmemora el 80 aniversario del desembarco de Normandía\n" +
                        "\n" +
                        "La reportera Martha Gellhorn colabora con The Ghost Army, un ejército fantasma creado en Hollywood para engañar a los nazis. Ella y su marido, el famoso Ernest Hemingway, inventan las vidas de soldados que no existen. Pero Martha aspira a mucho más; quiere cruzar el Atlántico y relatar de primera mano la etapa definitiva de la guerra.", valor: 15.43},
                {id: "5", nombre: "Todo lo que sé sobre el amor", autor: "Dolly Alderton", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/7b0b72bd-9b1c-43bb-a05d-f4cb8fca98ce/d_295_510/portada_todo-lo-que-se-sobre-el-amor_anna-valor-blanquer_201907111333.webp", sinopsis: "Tan salvajemente divertido y conmovedor como la vida de cualquier veinteañero que crece navegando entre desengaños amorosos y relaciones desastrosas.\n" +
                        "La periodista Dolly Alderton se propuso dar cuenta de sus locos veinte años en este divertido libro trufado de amores y desamores, relaciones intensas por Messenger que fracasan en el cara a cara, trabajos precarios y amigos que siempre están ahí. Un novio que acaba saliendo del armario, borracheras que te llevan a cruzar el país en taxis que no puedes pagar, chicos sin redes sociales que se creen Sartre…, escenas todas ellas de nuestra lucha por entender que el amor más intenso e importante es el que sentimos por nuestros amigos y nosotros mismos.", valor: 56.23},
                {id: "6", nombre: "El día D de Churchill", autor: "    Allen Packwood, Richard Dannatt", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/a7b64b2f-4495-4984-ad45-feeac0a9a064/d_295_510/portada_el-dia-d-de-churchill_allen-packwood_202404251032.webp", sinopsis: "La génesis, ejecución y secuelas del día D a través de los ojos del propio Winston Churchill.\n" +
                        "\n" +
                        "Al amanecer del 6 de junio de 1944, el desembarco de la mayor armada de buques jamás reunida comenzó a las 6:30 horas. Durante la noche, los paracaidistas aseguraron el flanco oriental de la zona de desembarco, mientras que otras Divisiones Aerotransportadas estadounidenses protegían el flanco occidental para evitar contraataques alemanes. Cuando Gran Bretaña se despertó con la noticia del desembarco, la declaración formal ante la Cámara de los Comunes recayó sobre su Primer Ministro, Winston Churchill. Aunque Churchill era consciente de la enorme responsabilidad que tenía para con los soldados británicos y los civiles franceses, y aunque sabía que sus oponentes políticos cuestionarían su liderazgo, apenas compartirá las conversaciones, los pensamientos más íntimos, las deliberaciones y las decisiones que ha estado tomando y que seguirá tomando en este día", valor: 85.23},
                {id: "7", nombre: "Las fieras", autor: "Clara Usón", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/dc3ceed0-b879-4add-989d-cfd5aa5d2c4c/d_295_510/portada_las-fieras_clara-uson_202404111014.webp", sinopsis: "Dos mujeres unidas por un asesinato sin resolver durante la guerra sucia entre ETA y los GAL.\n" +
                        "\n" +
                        "Idoia López Riaño, conocida como la Tigresa, fue una de las más sanguinarias terroristas de ETA y la que más atrajo la atención de los medios, tanto por sus atentados como por su belleza. Su historia, repleta de claroscuros, transcurre en paralelo a la de Miren, una adolescente que busca su lugar en el Euskadi de los años de plomo y que se esfuerza por parecer normal en una familia que no lo es, con un padre al que teme, un policía de la vieja escuela metido en la chapuza miserable de los GAL.", valor: 25.23},
                {id: "8", nombre: "Trilogía de la noche", autor: "Elie Wiesel", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/a6161f5f-524a-4ec7-8dc6-4805efcc6353/d_295_510/trilogia-de-la-noche_9788415325949.webp", sinopsis: "Un adolescente en los campos de exterminio nazis (La noche), el posterior periodo de reflexión en Palestina (El alba) y la historia de amor en Nueva York, consciente que la herida no se cerrará (El día).\n" +
                        "El autor, superviviente de los campos de concentración nazis, dedicó toda su vida a escribir y a hablar sobre los horrores del Holocausto con la firme intención de evitar que se repita en el mundo una barbarie similar.", valor: "$66.23"},
                {id: "9", nombre: "Las hermanas de Auschwitz", autor: "Roxane Van Iperen", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/d1010ee8-1e10-4278-8cf6-6f9f96679733/d_295_510/portada_las-hermanas-de-auschwitz_roxane-van-iperen_202405231035.webp", sinopsis: "La inolvidable historia de dos heroínas anónimas de la Segunda Guerra Mundial: las hermanas Janny y Lien Brilleslijper, que se unieron a la Resistencia holandesa, ayudaron a salvar docenas de vidas, fueron capturadas por los nazis y sobrevivieron al Holocausto.\n" +
                        "\n" +
                        "Al principio de la Segunda Guerra Mundial, tras la invasión nazi de Holanda, Janny y Lien Brilleslijper, dos hermanas judías, se unieron a la Resistencia. Escaparon de la ciudad hacia una casa perdida en medio del bosque que con el tiempo se convirtió en un lugar estratégico para la Resistencia y en un refugio para otros muchos perseguidos. No obstante, al año fueron detenidas y conducidas al campo de Westerbork, donde conocieron a Ana Frank y a su hermana Margot", valor: 42.23},
                {id: "10", nombre: "Detrás del ruido", autor: "Ángel Martín", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/7568ff39-66be-4825-8bc7-98bef7dbc8fe/d_295_510/portada_xx_aa-vv_202309041629.webp", sinopsis: "Tras el fenómeno editorial de Por si las voces vuelven, Ángel Martín regresa a las librerías con un libro íntimo e impactante —pero no exento de humor— sobre todo aquello que le ayudó a rehacerse y mantener la cordura, tras superar su brote psicótico.\n" +
                        "\n" +
                        "Desde que sufrí un brote psicótico y me ingresaron dos semanas en un psiquiátrico por escuchar voces que no podía controlar, presto una atención milimétrica a cualquier cosa que suceda dentro de mi cabeza.\n" +
                        "Cuando empezaba a salir del fondo del pozo en el que estuve, lo único que me importaba era descubrir qué podía hacer para recuperarme y estar bien.\n" +
                        "Pero cuando lo conseguí, mientras todo el mundo se alegraba, me di cuenta de que el reto en realidad no terminaba con volver a estar de pie. El verdadero reto era no volver a caerme.", valor: 55.23},
                {id: "11", nombre: "Música en la oscuridada", autor: "Antonio Iturbe", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/e1a33a52-eb0f-4296-96c7-6b1bf8a0f396/d_295_510/portada_musica-y-oscuridad_antonio-iturbe_202401081017.webp", sinopsis: "En el invierno de 1930, llegan al barrio rural de Las Casetas Joaquina y su marido, un clarinetista de la banda de Zaragoza, sastre de profesión, llamado Mariano. Ha sido contratado para hacerse cargo de la exigua banda municipal de esa localidad de gente trabajadora, mayormente agricultores sin formación. Enseguida conoce a los que han de ser los miembros de su banda: campesinos con los dedos deformes y las uñas negras sin ningún sentido musical. Pero nadie parece querer ponerselo fácil, ni siquiera funciona la pequeña sastrería que abre y es Joaquina la que debe trabajar en un horno de pan y vendiendo bocadillos en la estación para sacarlos adelante.\n" +
                        "  Sin embargo, poco a poco, Mariano conseguirá ganarse la confianza de esa gente ruda y él mismo aprenderá a confiar en ellos. Firme creyente en las ideas progresistas de modernizar el país a través de la educación y la cultura, realmente conseguirá, a través de su pasión por la música, mejorar las vida de estas personas. Frente a sus logros, emerge sin embargo una curandera a la que llaman \"la bruja\", empeñada en expulsar a Mariano y su esposa de la comunidad. Y entre ambos se establecerá un pulso entre razón y magia, rechazo y deseo, mientras la amenaza de la guerra avanza inexorablemente. ", valor: 45.33},
                {id: "12", nombre: "Operación pedestal", autor: "Max Hastings", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/28bec9a4-da91-47d4-a794-025114aee6e1/d_295_510/portada_operacion-pedestal_max-hastings_202405091518.webp", sinopsis: "En agosto de 1942, una asediada Malta estuvo a pocas semanas de rendirse porque sus 300.000 habitantes ya no podían ser alimentados. Churchill tomó la decisión personal de salvar a toda costa la “isla fortaleza”. No se trataba simplemente de una cuestión de estrategia, sino de prestigio nacional, cuando la fortuna y la moral de Gran Bretaña habían caído a su punto más bajo.\n" +
                        "\n" +
                        "Por las páginas de este libro veremos desfilar catastróficos hundimientos de buques, junto con luchas por rescatar a los supervivientes y salvar los barcos siniestrados. Max Hastings describe esta historia como una de las más extraordinarias que jamás haya contado. Hasta las últimas horas, ningún participante de ninguno de los dos bandos pudo saber cuál sería el resultado de una epopeya de suspense y valor en tiempos de guerra.", valor: 67.33},
                {id: "13", nombre: "Historia de España para escépticos", autor: "Juan Eslava Galán", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/da14bd4e-0adb-49fe-805b-cb2a6330fe7d/d_295_510/portada_historia-de-espana-contada-para-escepticos_juan-eslava-galan_201706061807.webp", sinopsis: "Desde la prehistoria hasta Podemos, el autor repasa la historia de nuestro país narrándola de una forma original y amena que enganchará a los lectores.\n" +
                        "\n" +
                        "Es esta una historia de España que, tal como nos cuenta el propio autor, no pretende ser veraz, justa y desapasionada, porque ninguna historia lo es. No está hecha para halagar a reyes y gobernantes, ni pretende halagar a los banqueros, ni a la Conferencia Episcopal, ni al colectivo gay, ni a los filatélicos, ni a los sindicatos.\n" +
                        "\n" +
                        "Es esta una obra que consigue enseñar, informar y entretener a partes iguales, escrita con el inconfundible estilo divulgativo de Eslava Galán, donde el relato de los grandes acontecimientos se suma al de las anécdotas más curiosas y desconocidas de los protagonistas de nuestra historia.\n" +
                        "\n" +
                        "Por todo, una obra que no hay que perderse. ", valor: 42.13},
                {id: "14", nombre: "Madre de corazón atómico", autor: "Agustín Fernández Mallo", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/fb89ec71-9dda-42bc-b38b-234d7da65e53/d_295_510/portada_madre-de-corazon-atomico_agustin-fernandez-mallo_202404150949.webp", sinopsis: "En 1967, poco antes del nacimiento de Agustín Fernández Mallo, su padre, un hombre nacido un pequeño pueblo leonés, veterinario de profesión y firme creyente en la ciencia y el progreso, se embarcó en un viaje pionero por Estados Unidos con el objetivo de traer una veintena de vacas en un avión hasta Galicia. Casi medio siglo después, será el escritor quien realice su propio periplo por tierras americanas, tratando de reconstruir los pasos de su progenitor antes de que éste pierda la memoria.\n" +
                        "  Madre de corazón atómico recorre un siglo de Historia de España a través de una red de historias y leyendas familiares, de gente anónima que ha vivido la guerra civil, la posguerra, la democracia y el cambio de siglo. Como afirma el narrador, «la vida escribe la ficción que nosotros jamás nos atreveremos a escribir».", valor: 72.23},
                {id: "15", nombre: "Almudena", autor: "Luis García Montero", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/f5ce4415-c4a0-45bb-ad30-13f767617eb9/d_295_510/portada_almudena_luis-garcia-montero_202403070940.webp", sinopsis: "Cuando Luis García Montero escribió Un año y tres meses («Una conmovedora lección de duelo» Luis Bagué Quílez, El País; «Una tabla de salvación ante el naufragio» Josep Cuní, El Periódico) para contar la convalecencia y la despedida de su mujer, la escritora Almudena Grandes, en realidad había compuesto el capítulo final de una larga historia de amor que se inició muchos años antes y que había ido contando, como en un hilo rojo, en composiciones dedicadas a ella en sus sucesivos libros de poesía.   Almudena reúne los poemas de amor que el autor le fue dedicando a su mujer entre 1994 y 2021, y puede leerse como una historia completa que va del enamoramiento en Completamente viernes, hasta la vida en pareja de La intimidad de la serpiente, los afectos de madurez de Vista cansada, los compromisos compartidos de Un invierno propio, la complicidad de A puerta cerrada, y la resistencia en común de No puedes ser así. Breve historia del mundo.", valor: "$16.23"},
                {id: "16", nombre: "Dime que sientes", autor: "Jesús Martín-Fernández", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/8fda15b5-10f7-437d-abdb-04fdb6b7daf8/d_295_510/portada_dime-que-sientes_jesus-martin-fernandez_202402290856.webp", sinopsis: "En febrero de 2023, el doctor Jesús Martín-Fernández llevó a cabo, con éxito, la primera cirugía cerebral despierta en la que utilizó un test de inteligencia artificial para identificar y preservar las emociones del paciente. Con este hito, no solo revoluciona la medicina actual, sino que abre la puerta a nuevas y fascinantes teorías sobre el órgano más misterioso del cuerpo humano, el cerebro. \n" +
                        "\n" +
                        "Con gran destreza narrativa y a través de un relato sincero y sin tapujos, el doctor Martín-Fernández nos invita a su quirófano para vivir en primera persona la emoción y la responsabilidad de tener en sus manos la vida de sus pacientes. Nos adentraremos en las historias de pacientes con tumores cerebrales de extrema complejidad, como el caso de Yolanda —la primera persona con la que se utilizó el test de inteligencia artificial para conservar las emociones—, el de un pianista al que se le practicó una cirugía a la carta para proteger sus habilidades musicales, una intérprete políglota quien debe mantener sus cinco idiomas, o incluso el testimonio de un paciente que describe con detalle cómo vivió una experiencia extracorpórea durante la operación", valor: 72.23},
                {id: "17", nombre: "El juego del dinero", autor: "Gary Stevenson", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/52af911c-ea67-48ad-9949-19a8039850f7/d_295_510/portada_el-juego-del-dinero_gary-stevenson_202404231132.webp", sinopsis: "Esta es la historia real, contada en primera persona, de un chaval del sur obrero de Londres que poco a poco y gracias a su talento matemático consigue ir ascendiendo hasta la cúspide de uno de esos rascacielos de la City que de pequeño oteaba con envidia y admiración. Un trayecto que le lleva desde sus años en la London School of Economics, vestido con una sudadera que llama la atención de sus compañeros con trajes a medida, hasta su ascenso en Citybank.\n" +
                        "\n" +
                        "Escrito son sorna, el libro disecciona esa clase privilegiada que se enriquece a ritmo frenético gracias al empobrecimiento del resto, y nos sumerge en un mundo de lujos, fiestas y excesos que dan cuenta de la absoluta falta de ética que rige en la élite financiera. Convertido hoy en un activista contra la desigualdad y los desmanes de los especuladores, Gary Stevenson retrata a los miembros de esa feria de las vanidades que gobierna el mundo y a la que ni la peor de las crisis pudo derribar.", valor: 29.61},
                {id: "18", nombre: "Episodios nacionales I. La guerra de la independencia", autor: "Benito Pérez Galdós", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/7040d9f1-725c-4e5a-8d41-6e60e541ce6b/d_295_510/portada_episodios-nacionales-i-la-guerra-de-la-independencia_benito-perez-galdos_201505260928.webp", sinopsis: "La guerra de la Independencia es la gran novela de la historia. Las innumerables peripecias que vive Gabriel y su azarosa relación de amor con Inés se entrelazan a la aventura bélica y política en la que España vivió inmersa durante más de seis años. Su relato abarca desde el 21 de octubre de 1805, cuando lucha como grumete en Trafalgar, hasta el 22 de julio de 1812, cuando ya veterano capitán culmina una hazaña de espionaje en los Arapiles, principio del fin de la ocupación francesa.\n" +
                        "\n" +
                        "La guerra de la Independencia reúne la primera serie de los Episodios nacionales de Benito Pérez Galdós: Trafalgar, La corte de Carlos IV, El 19 de marzo y el 2 de mayo, Bailén, Napoleón en Chamartín, Zaragoza, Gerona, Cádiz, Juan Martín el Empecinado y La batalla de los Arapiles.", valor: 77.23},
                {id: "19", nombre: "Episodios de una guerra interminable", autor: "Pack Episodios de una guerra interminable", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/3357838a-8adb-4b6a-bf03-3db64b773c14/d_295_510/portada_pack-episodios-de-una-guerra-interminable_almudena-grandes_202204051539.webp", sinopsis: "Cuando en 2010 Almudena Grandes publicó Inés y la alegría, en la que novelizó de manera inolvidable el episodio desconocido de la toma del valle de Arán en 1944 por un ejército de republicanos españoles, anunció que con ella iniciaba una serie de novelas independientes con las que querían trazar la historia olvidada de los que resistieron y lucharon en la clandestinidad durante la posguerra y el franquismo. Así aparecieron El lector de Julio Verne, sobre el maquis en la sierra de Jaén, Las tres bodas de Manolita, sobre la organización de la resistencia en Madrid, entre cárceles, tablaos y Cuelgamuros, Los pacientes del doctor García, sobre la red de evasión de nazis en la España franquista, y La madre de Frankenstein, en el que un manicomio se convierte en microcosmos de un régimen represor. Esas cinco novelas forman el último gran friso de la literatura española, una obra titánica que ha logrado una repercusión irrepetible, y que ahora ofrecemos en un pack de lujo.", valor: 51.88},
                {id: "20", nombre: "El tatuador de Auschwitz", autor: "Heather Morris", image: "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/e6931dbb-fa5a-4500-8faf-d854343c6701/d_295_510/portada_el-tatuador-de-auschwitz_heather-morris_202310231126.webp", sinopsis: "Para Lale, los días transcurren entre el horror y su trabajo como tatuador de prisioneros. Entre estos prisioneros se encuentra Gita, una joven de la que queda enamorado. En ese momento, la vida de Lale cobrará un nuevo sentido y hará todo lo posible para que Gita y el resto de prisioneros sobrevivan.\n" +
                        "\n" +
                        "Después de la guerra, deciden mudarse a Australia para poder comenzar de nuevo. Tras la muerte de Gita, Lale siente el peso de su pasado y la irremediable necesidad de contarlo. Esta es su historia. ", valor: 7.95},

        ];
